<%
'===============================================================
' Type Info: IOMode, TypeInfo Version 0.000
' GUID: {00000000-0000-0000-0000-000000000000}
' LCID: 0X00000000
' TypeKind: enum
'---------------------------------------------------------------

' Variable/Constant: ForReading
' 
Const ForReading = 1

' Variable/Constant: ForWriting
' 
Const ForWriting  = 2

' Variable/Constant: ForAppending
' 
Const ForAppending = 8

'===============================================================
' Type Info: Tristate, TypeInfo Version 0.000
' GUID: {00000000-0000-0000-0000-000000000000}
' LCID: 0X00000000
' TypeKind: enum
'---------------------------------------------------------------

' Variable/Constant: TristateTrue
' 
Const TristateTrue = -1

' Variable/Constant: TristateFalse
' 
Const TristateFalse = 0

' Variable/Constant: TristateUseDefault
' 
Const TristateUseDefault = -2

' Variable/Constant: TristateMixed
' 
Const TristateMixed = -2
%>